Add extra steps to set_env_vars_for_maven

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -48,6 +48,9 @@ jobs:
       - cloudsmith-maven/set_env_vars_for_maven:
           repository: "circleci-orb-testing"
       - run:
+          name: cd into maven project directory
+          command: cd simple-maven-project
+      - run:
           name: Install package dependencies
           command: mvn install
 
@@ -65,6 +68,16 @@ jobs:
             if [ -z $CLOUDSMITH_MAVEN_REGISTRY ]
             then
               echo "Test failed: CLOUDSMITH_MAVEN_REGISTRY has not been set."
+              exit 1
+            fi
+            if [ -z "$CLOUDSMITH_REPOSITORY" ]
+            then
+              echo "Unable to configure MAVEN. Env var CLOUDSMITH_REPOSITORY is not defined. Please run the set_env_vars_for_maven command first."
+              exit 1
+            fi
+            if [ -z "$CLOUDSMITH_OIDC_TOKEN" ]
+            then
+              echo "Unable to configure MAVEN. Env var CLOUDSMITH_OIDC_TOKEN is not defined. Please run the set_env_vars_for_maven command first."
               exit 1
             fi
             echo "All tests passed."
@@ -87,7 +100,7 @@ workflows:
       - orb-tools/pack:
           filters: *release-filters
       - orb-tools/publish:
-          orb_name: ft-circleci-orbs/cloudsmith-npm
+          orb_name: ft-circleci-orbs/cloudsmith-maven
           vcs_type: << pipeline.project.type >>
           pub_type: production
           # Ensure this job requires all test jobs and the pack job.
