Refactor to accommodate for CLOUDSMITH_REPOSITORY_UNSTABLE

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -42,6 +42,11 @@ jobs:
               echo "Unable to configure MAVEN. Env var CLOUDSMITH_REPOSITORY is not defined. Please run the set_env_vars_for_maven command first."
               exit 1
             fi
+            if [ -z "$CLOUDSMITH_REPOSITORY_UNSTABLE" ]
+            then
+              echo "Unable to configure MAVEN. Env var CLOUDSMITH_REPOSITORY_UNSTABLE is not defined. Please run the set_env_vars_for_maven command first."
+              exit 1
+            fi
             if [ -z "$CLOUDSMITH_OIDC_TOKEN" ]
             then
               echo "Unable to configure MAVEN. Env var CLOUDSMITH_OIDC_TOKEN is not defined. Please run the set_env_vars_for_maven command first."
